cooldown_secs: 60
kill_switch_pct: 0.2
feature_format: parquet
min_signal_score_entry: 0.3
meta_filter_threshold: 0.5
meta_filter_relaxed_threshold: 0.45
meta_filter_relax_blocks: 5

data:
  data_dir: 'data'
  parquet_dir: 'data/parquet_cache'
  path: 'XAUUSD_M1.csv'

# Exchange/Broker/API integration config
trading:
  enabled: true
  mode: demo   # demo, real, backtest
  exchange: 'binance'  # binance, bitkub, alpaca, etc.
  api_url: 'https://api.binance.com/api/v3/order'
  api_key: 'YOUR_API_KEY_HERE'
  api_secret: 'YOUR_API_SECRET_HERE'
  webhook_url: 'https://your-webhook-endpoint.com/trade'
  # เพิ่ม exchange/broker อื่น ๆ ได้ตามต้องการ
