"""
config_defaults.py: กำหนดค่าตัวแปร default ต่างๆ ที่ใช้ใน pipeline/main
"""
import os
from src.utils import get_env_float

# กำหนดค่าตัวแปร default ต่างๆ ที่เดิมอยู่ใน main.py
DEFAULT_OUTPUT_DIR = "./output_default"
DEFAULT_META_CLASSIFIER_PATH = "meta_classifier.pkl"
DEFAULT_SPIKE_MODEL_PATH = "meta_classifier_spike.pkl"
DEFAULT_CLUSTER_MODEL_PATH = "meta_classifier_cluster.pkl"
DEFAULT_FUND_NAME = "NORMAL"
DEFAULT_MODEL_TO_LINK = "catboost"
DEFAULT_ENABLE_OPTUNA_TUNING = True
DEFAULT_SAMPLE_SIZE = None
DEFAULT_FEATURES_TO_DROP = None
DEFAULT_MULTI_FUND_MODE = True
DEFAULT_FUND_PROFILES = {}
DEFAULT_TRAIN_META_MODEL_BEFORE_RUN = True
DEFAULT_META_CLASSIFIER_FEATURES = []
DEFAULT_RECOVERY_MODE_CONSECUTIVE_LOSSES = 4
DEFAULT_TIMEFRAME_MINUTES_M15 = 15
DEFAULT_DRIFT_WASSERSTEIN_THRESHOLD = get_env_float("DRIFT_WASSERSTEIN_THRESHOLD", 0.1)
DEFAULT_DRIFT_TTEST_ALPHA = 0.05
DEFAULT_INITIAL_CAPITAL = 100.0
DEFAULT_N_WALK_FORWARD_SPLITS = 5
_BASE_DIR = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
DEFAULT_OUTPUT_BASE_DIR = os.path.join(_BASE_DIR, "logs")
DEFAULT_OUTPUT_DIR_NAME = "outputgpt_v4.8.4"
DEFAULT_DATA_FILE_PATH_M15 = os.path.join(_BASE_DIR, "XAUUSD_M15.csv")
DEFAULT_DATA_FILE_PATH_M1 = os.path.join(_BASE_DIR, "XAUUSD_M1.csv")
DEFAULT_META_META_CLASSIFIER_PATH = "meta_meta_classifier.pkl"
DEFAULT_USE_META_CLASSIFIER = True
DEFAULT_META_MIN_PROBA_THRESH = 0.25
DEFAULT_REENTRY_MIN_PROBA_THRESH = 0.5
DEFAULT_USE_META_META_CLASSIFIER = False
DEFAULT_META_META_MIN_PROBA_THRESH = 0.5
DEFAULT_OPTUNA_N_TRIALS = 50
DEFAULT_OPTUNA_CV_SPLITS = 5
DEFAULT_OPTUNA_METRIC = "AUC"
DEFAULT_OPTUNA_DIRECTION = "maximize"
DEFAULT_USE_GPU_ACCELERATION = True
DEFAULT_ENABLE_FORCED_ENTRY = True
DEFAULT_FORCED_ENTRY_BAR_THRESHOLD = 100
DEFAULT_FORCED_ENTRY_MIN_SIGNAL_SCORE = 0.5
DEFAULT_FORCED_ENTRY_LOOKBACK_PERIOD = 500
DEFAULT_FORCED_ENTRY_CHECK_MARKET_COND = True
DEFAULT_FORCED_ENTRY_MAX_ATR_MULT = 2.5
DEFAULT_FORCED_ENTRY_MIN_GAIN_Z_ABS = 0.5
DEFAULT_FORCED_ENTRY_ALLOWED_REGIMES = [
    "Normal",
    "Breakout",
    "StrongTrend",
    "Reversal",
    "InsideBar",
    "Choppy",
]
DEFAULT_FE_ML_FILTER_THRESHOLD = 0.40
DEFAULT_MIN_SIGNAL_SCORE_ENTRY = 1.0
DEFAULT_RISK_PER_TRADE = 0.01
DEFAULT_MAX_DRAWDOWN_THRESHOLD = 0.30
DEFAULT_ENABLE_PARTIAL_TP = True
DEFAULT_PARTIAL_TP_LEVELS = [{"r_multiple": 0.8, "close_pct": 0.5}]
DEFAULT_PARTIAL_TP_MOVE_SL_TO_ENTRY = True
DEFAULT_ENABLE_KILL_SWITCH = True
DEFAULT_KILL_SWITCH_MAX_DD_THRESHOLD = 0.15
DEFAULT_KILL_SWITCH_CONSECUTIVE_LOSSES_THRESHOLD = 5
DEFAULT_KILL_SWITCH_WARNING_MAX_DD_THRESHOLD = 0.25
DEFAULT_KILL_SWITCH_WARNING_CONSECUTIVE_LOSSES_THRESHOLD = 7
DEFAULT_forced_entry_max_consecutive_losses = 2
DEFAULT_min_equity_threshold_pct = 0.70
DEFAULT_IB_COMMISSION_PER_LOT = 7.0
DEFAULT_EARLY_STOPPING_ROUNDS = 200
DEFAULT_CATBOOST_GPU_RAM_PART = 0.95
DEFAULT_SHAP_IMPORTANCE_THRESHOLD = 0.01
DEFAULT_PERMUTATION_IMPORTANCE_THRESHOLD = 0.001
